### ISSUE TITLE
Setup Baseline User Authentication

### ISSUE THREAD

**Issue by joshua-tyh** [bibblepets/bibble#12]
### Issue Overview

Currently, the repository lacks a basic user authentication system. This issue is created to address the setup of a user auth system using JWT.

### Proposed Solution

- Implement a basic user authentication system for secure access.

### Tasks:

- [x] Integrate a baseline user authentication system (e.g., using JWT).
- [x] Create user registration, login, and logout routes/handlers.

### Additional Information

- [JWT Authentication in Node.js](https://www.npmjs.com/package/jsonwebtoken)

**Comment by joshua-tyh** [comment]
### New Issue
Currently, all routes can be publicly accessed. This is because there is not proper check for user authentication when accessing routes and needs to be fixed.

### Additional Tasks:
- [ ] Implement user authentication middleware for protected routes.
